function(zen_enable_sanitizers tgt)
    if(NOT ZEN_ENABLE_SANITIZERS)
        return()
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        target_compile_options(${tgt} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
        target_link_options(${tgt}    PRIVATE -fsanitize=address,undefined)
    elseif(MSVC)
        target_compile_options(${tgt} PRIVATE /fsanitize=address)
    endif()
endfunction()
